# Generated by Django 5.2.5 on 2025-10-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('One', 'One (High)'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five (Low)')], max_length=10)),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Social', 'Social'), ('Financial', 'Financial'), ('School', 'School'), ('Health', 'Health')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
