# Generated by Django 5.2.5 on 2025-10-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_category_remove_task_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Social', 'Social'), ('Financial', 'Financial'), ('School', 'School'), ('Health', 'Health')], default='Personal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('One', 'One (High)'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five (Low)')], default='Personal', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
